### ISSUE TITLE
Problem with Maven Pom: "de.dfki.mary" and "voice-bits3"

### ISSUE THREAD

**Issue by KujaEx** [hainoon/wikipediareader#2]
Hello, I try to get your framework running but when opening the maven project it says following dependency artifacts don't exists (and I really can't find them online in maven repos).

		<dependency>
			<groupId>de.dfki.mary</groupId>
			<artifactId>marytts-runtime</artifactId>
			<version>5.2</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/marytts-runtime-5.2-SNAPSHOT-jar-with-dependencies.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>de.dfki.mary</groupId>
			<artifactId>marytts-client</artifactId>
			<version>5.2</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/marytts-client-5.2-SNAPSHOT-jar-with-dependencies.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>de.dfki.mary</groupId>
			<artifactId>marytts-lang-de</artifactId>
			<version>5.2</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/marytts-lang-de-5.2-SNAPSHOT.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>voice-bits3</groupId>
			<artifactId>voice-bits3</artifactId>
			<version>3-5.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/voice-bits3-5.1.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>de.dfki.mary</groupId>
			<artifactId>voice-cmu-slt-hsmm</artifactId>
			<version>5.2</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/voice-cmu-slt-hsmm-5.2-SNAPSHOT.jar</systemPath>
		</dependency>

I already tried to get this jar files online. The project is running, but throws exceptions immediately at the beginning, so I guess this problem with maven should be solved first.

**Comment by timobaumann** [comment]
thanks for reporting this. I have pushed a fix in 4d2d7c8, however the software then runs into other errors afterwards during synthesis of the article (unless you have our pre-processed spoken articles at hand)
I'm tracking that problem in issue #3. Also, I'll work towards making a few spoken articles (and all the necessary files that go with them) available (which I'll track in issue #4 ).
